-- CreateTable
CREATE TABLE `hw233Ota` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `ota_value` INTEGER NOT NULL,
    `ota_voltage` DOUBLE NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
